// Curated landmark list. Positions are resolved against OpenStreetMap at data-build time
// (`match` = regex against OSM names, `building` = regex against named building footprints);
// lat/lon are fallbacks. Facts are hand-verified; the app adds live Wikipedia/Wikidata facts on top.
export const LANDMARKS = [
  {
    id: 'aga-khan-palace',
    name: 'Aga Khan Palace',
    category: 'heritage',
    match: 'Aga\\s*Khan\\s*Palace|Gandhi National Memorial',
    building: 'Aga\\s*Khan\\s*Palace',
    preferStation: false,
    lat: 18.5523, lon: 73.9015,
    wikipedia: 'Aga Khan Palace',
    wikidata: 'Q2344976',
    importance: 1,
    tagline: 'Famine-relief palace turned Gandhi’s prison',
    facts: [
      'Aga Khan III ordered the palace in 1892 as a famine-relief project, to give work to hungry villagers from the surrounding area.',
      'After the Quit India call, Mahatma Gandhi, Kasturba Gandhi and his secretary Mahadev Desai were interned here from 9 August 1942 to 6 May 1944.',
      'Both Kasturba Gandhi and Mahadev Desai died during that captivity; their marble samadhis stand in the grounds, and a portion of Gandhi’s own ashes was added in 1992.',
      'In 1969 Aga Khan IV donated the palace to the Indian people in honour of Gandhi. It later housed a school (1953–72) and served as a filming location for the movie "Gandhi".',
      'A 2.5-metre-wide corridor wraps around the entire building, the palace’s signature architectural feature.',
    ],
    sources: [
      'https://en.wikipedia.org/wiki/Aga_Khan_Palace',
      'https://en.wikipedia.org/wiki/Yerawada',
    ],
  },
  {
    id: 'viman-nagar',
    name: 'Viman Nagar',
    category: 'neighbourhood',
    match: 'Viman\\s*Nagar|Vimannagar',
    preferStation: false,
    lat: 18.5670, lon: 73.9130,
    wikipedia: 'Vimannagar',
    wikidata: 'Q36123',
    importance: 2,
    tagline: 'The “Airport City” on Pune’s east side',
    facts: [
      'The name literally means "Airport City" in Marathi, because it sits right at the southern edge of Pune Airport.',
      'Before Independence the area was known as "Dunkirk Lines".',
      'Several Symbiosis institutes, including Symbiosis Law School, are based here, and the neighbourhood has some of the highest property prices in Maharashtra.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Vimannagar'],
  },
  {
    id: 'kalyani-nagar',
    name: 'Kalyani Nagar',
    category: 'neighbourhood',
    match: '^Kalyani\\s*Nagar$',
    preferStation: false,
    lat: 18.5481, lon: 73.9026,
    wikipedia: 'Kalyani Nagar',
    wikidata: 'Q6354979',
    importance: 2,
    tagline: 'Riverside suburb named after an industrialist',
    facts: [
      'It is named after industrialist Neelkanth Kalyani, founder of Kalyani Forging in the early 1960s, who was one of the area’s first residents and brought in electricity and water supply.',
      'The neighbourhood grew rapidly after the H. H. Aga Khan Bridge was built across the Mula-Mutha, linking it to Koregaon Park.',
      'In November 2018 residents protested the metro route through the area over fears for the trees and wildlife of the nearby Salim Ali Bird Sanctuary.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Kalyani_Nagar'],
  },
  {
    id: 'koregaon-park',
    name: 'Koregaon Park',
    category: 'neighbourhood',
    match: '^Koregaon\\s*Park$',
    preferStation: false,
    lat: 18.5362, lon: 73.8940,
    wikipedia: 'Koregaon Park',
    wikidata: 'Q6432111',
    importance: 1,
    tagline: 'British-era estate turned nightlife hub',
    facts: [
      'It began in the early 1920s as "Koregaon Road Estate", a British colonial settlement laid out on the lands of Ghorpuri village just outside Pune.',
      'The estate’s plots were auctioned off, many to rich merchants and India’s princely families, which is why it has stayed one of Pune’s most up-market areas.',
      'It was renamed Koregaon Park to avoid confusion with Koregaon Bhima village after the old Koregaon Road was renamed Ahmednagar Road.',
      'Its leafy lanes hold the Osho meditation resort and a Jewish Chabad house; in 2010 a bomb at the German Bakery here killed 18 people.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Koregaon_Park'],
  },
  {
    id: 'pune-airport',
    name: 'Pune International Airport',
    category: 'airport',
    match: 'Pune\\s*(International\\s*)?Airport|Lohe?gaon\\s*Air\\s*Force|Pune Airport',
    building: 'Terminal|Pune\\s*Airport',
    preferStation: false,
    lat: 18.5822, lon: 73.9197,
    wikipedia: 'Pune Airport',
    wikidata: 'Q1432525',
    importance: 1,
    tagline: 'Civil enclave on an Air Force base',
    facts: [
      'It is not a standalone airport: the civil terminal is an enclave on the western side of Lohegaon Air Force Station, and air traffic control is run by the Indian Air Force.',
      'The airfield opened in 1939 as RAF Poona and hosted World War II squadrons of Mosquito and Wellington bombers and Spitfire fighters.',
      'Lufthansa’s Frankfurt service (from 2008) used a business-class-only Airbus A319, because the short 2,540 m runway ruled out a bigger jet.',
      'A proposal to rename it Jagadguru Sant Tukaram Maharaj Airport has been approved by the state government.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Pune_Airport'],
  },
  {
    id: 'mula-mutha',
    name: 'Mula-Mutha River',
    category: 'river',
    match: 'Mula[\\s-]*Mutha',
    preferStation: false,
    lat: 18.5445, lon: 73.8930,
    wikipedia: 'Mula-Mutha River',
    wikidata: 'Q6933703',
    importance: 1,
    tagline: 'Two rivers merged, bound for Bengal',
    facts: [
      'It forms where the Mula and Mutha rivers meet inside Pune, then flows into the Bhima and on to the Krishna, which empties into the Bay of Bengal on India’s opposite coast.',
      'Effluent from Pune has been found to pollute the Bhima, the Ujani dam reservoir and even the Krishna further downstream.',
      'In 2014 Pune Police discovered marijuana plants being grown on the riverbed near Kharadi.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Mula-Mutha_River'],
  },
  {
    id: 'bund-garden',
    name: 'Bund Garden (Mahatma Gandhi Udyan)',
    category: 'park',
    match: 'Bund\\s*Garden|Bandh\\s*Garden|Mahatma\\s*Gandhi\\s*Udyan',
    preferStation: false,
    lat: 18.5416, lon: 73.8847,
    wikipedia: 'Bund Garden, Pune',
    wikidata: 'Q4997473',
    importance: 2,
    tagline: 'Garden named after a river dam',
    facts: [
      'The name comes from the "bund", a small dam on the river built by Parsi philanthropist Jamsetjee Jejeebhoy to supply irrigation water to the poor.',
      'It opened in 1869 once the adjacent bridge was complete, laid out by Colonel Sellon, who turned waste ground into a garden.',
      'Today it is officially called Mahatma Gandhi Udyan.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Bund_Garden,_Pune'],
  },
  {
    id: 'fitzgerald-bridge',
    name: 'Fitzgerald Bridge',
    category: 'bridge',
    match: 'Fitz\\s*gerald\\s*Bridge|Bund\\s*Garden\\s*Bridge',
    preferStation: false,
    lat: 18.5433, lon: 73.8849,
    wikipedia: 'Fitzgerald Bridge, Pune',
    wikidata: 'Q24906423',
    importance: 2,
    tagline: '1867 arch bridge guarded by lions',
    facts: [
      'Built in 1867, it was the first spandrel arch bridge in Pune, and a Medici lion sits at each end.',
      'It was designed by Captain Robert Sellon of the Royal Engineers and named after Sir William Robert Vesey Fitzgerald, then Governor of Bombay.',
      'Having outlived its design life, it was spared demolition: it was closed to vehicles and turned into a space for arts and artisans.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Fitzgerald_Bridge,_Pune'],
  },
  {
    id: 'osho-teerth',
    name: 'Osho Teerth Park',
    category: 'park',
    match: 'Osho\\s*Teerth|Nal?la\\s*Park',
    preferStation: false,
    lat: 18.5363, lon: 73.8908,
    wikipedia: null,
    wikidata: null,
    importance: 2,
    tagline: 'Zen garden grown on a sewage ditch',
    facts: [
      'The park was built on a wasteland around a polluted nala (stream) — Osho News describes a "parched wasteland" with "a mere trickle of brackish water" — and was first nicknamed "Nalla Park".',
      'Trains dumped waste oil into the stream and the neighbouring village’s sewage ended up in it too, so the designers built screens to catch the oil before landscaping.',
      'The water is cleaned naturally: it flows through shallow settling ponds aerated by fountains and filtered by water hyacinths.',
    ],
    sources: [
      'https://www.oshonews.com/2021/08/24/osho-teerth-park-designing-paradise/',
      'https://en.wikipedia.org/wiki/Koregaon_Park',
    ],
  },
  {
    id: 'osho-resort',
    name: 'Osho International Meditation Resort',
    category: 'religious',
    match: 'Osho\\s*(International\\s*)?(Meditation\\s*Resort|Ashram|Commune)',
    building: 'Osho',
    preferStation: false,
    lat: 18.5369, lon: 73.8886,
    wikipedia: null,
    wikidata: null,
    importance: 1,
    tagline: 'The guru Osho’s ashram, now a resort',
    facts: [
      'Osho (Rajneesh) moved here in 1974, to a property bought with the help of Greek shipping heiress Catherine Venizelos (Ma Yoga Mukta).',
      'He left for a commune in Oregon in 1981 — where he became known as the "Rolls-Royce guru" — and returned to this ashram in January 1987, dying here in 1990.',
      'His ashes rest in Lao Tzu House, under the epitaph: "Never Born – Never Died. Only visited this planet Earth between December 11, 1931 and January 19, 1990".',
      'It bills itself as the "Esalen of the East"; as of 2013 every guest had to take an HIV test on arrival, and maroon robes are worn on the premises.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Osho'],
  },
  {
    id: 'kalyani-nagar-metro',
    name: 'Kalyani Nagar metro station',
    category: 'transit',
    match: 'Kalyani\\s*Nagar',
    preferStation: true,
    lat: 18.5445, lon: 73.9057,
    wikipedia: 'Kalyani Nagar metro station',
    wikidata: 'Q124793273',
    importance: 2,
    tagline: 'Aqua Line stop on East Avenue',
    facts: [
      'It opened on 6 March 2024 as part of the Aqua Line extension to Ramwadi.',
      'The route through Kalyani Nagar was contested: residents protested in 2018 over trees and wildlife near the Salim Ali Bird Sanctuary.',
      'An extra entrance (Gate 3) opened in June 2024 so riders could reach the platform by footbridge without crossing the busy road.',
    ],
    sources: [
      'https://en.wikipedia.org/wiki/Kalyani_Nagar_metro_station',
      'https://en.wikipedia.org/wiki/Kalyani_Nagar',
    ],
  },
  {
    id: 'ramwadi-metro',
    name: 'Ramwadi metro station',
    category: 'transit',
    match: 'Ramwadi',
    preferStation: true,
    lat: 18.5570, lon: 73.9086,
    wikipedia: 'Ramwadi metro station',
    wikidata: 'Q124793263',
    importance: 2,
    tagline: 'Eastern end of the Aqua Line',
    facts: [
      'It is the eastern terminus of the Aqua Line, which runs 14.66 km west to Vanaz.',
      'When it opened in March 2024 an AC feeder bus ran from here to the airport for just ₹5–10; the shuttle later moved to Yerwada station.',
      'Phoenix Marketcity mall is only about 300 m away.',
    ],
    sources: [
      'https://en.wikipedia.org/wiki/Ramwadi_metro_station',
      'https://en.wikipedia.org/wiki/Phoenix_Marketcity,_Pune',
    ],
  },
  {
    id: 'phoenix-marketcity',
    name: 'Phoenix Marketcity',
    category: 'mall',
    match: 'Phoenix\\s*Market\\s*City|Phoenix\\s*Marketcity|Phoenix\\s*Avenue\\s*of\\s*Stars',
    building: 'Phoenix',
    preferStation: false,
    lat: 18.5621, lon: 73.9167,
    wikipedia: 'Phoenix Marketcity, Pune',
    wikidata: 'Q24091457',
    importance: 1,
    tagline: 'One of India’s largest malls',
    facts: [
      'Opened in June 2011, it is one of the largest malls in India, with about 1.19 million sq ft of retail space.',
      'It has since been rebranded "Phoenix Avenue of Stars", the name now used on Wikipedia and OpenStreetMap.',
      'It was developed by Phoenix Mills Limited, and Ramwadi metro station is about 300 m away.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Phoenix_Marketcity,_Pune'],
  },
  {
    id: 'kopa-mall',
    name: 'KOPA',
    category: 'mall',
    match: '^(The\\s*)?KOPA(\\s*Mall)?$',
    building: 'KOPA',
    preferStation: false,
    lat: 18.5384, lon: 73.9077,
    wikipedia: null,
    wikidata: null,
    importance: 2,
    tagline: 'Pune’s luxury mall, rebuilt from an old one',
    facts: [
      'KOPA opened on 21 October 2023 at the eastern edge of Koregaon Park. Its official address is Mundhwa Road, Village Ghorpadi.',
      'It isn’t a new build: developer Lake Shore bought an older mall on the site in 2019 and completely redeveloped it into a 3.25 lakh sq ft luxury centre.',
      'Around 30–40 international brands made their Pune debut here, and the mall is pet-friendly.',
      'Its open-air "Village" district packs seven restaurants and two rooftop lounges.',
    ],
    sources: [
      'https://kopapune.com/press-release/',
      'https://www.punekarnews.in/kopa-mall-in-pune-30-to-40-international-brands-debut-in-koregaon-park-can-also-visit-with-pets/',
      'https://businessindia.co/magazine/corporate-report/redefining-urban-retail',
    ],
  },
  {
    id: 'yerwada-jail',
    name: 'Yerwada Central Jail',
    category: 'heritage',
    match: 'Yer[a]?[wv]a?da\\s*(Central\\s*)?(Jail|Prison)',
    preferStation: false,
    lat: 18.5646, lon: 73.8897,
    wikipedia: 'Yerawada Central Jail',
    wikidata: 'Q142534',
    importance: 1,
    tagline: 'Where the Poona Pact was signed',
    facts: [
      'On 24 September 1932, Gandhi ended a fast against the Communal Award by signing the Poona Pact with B. R. Ambedkar inside this jail.',
      'Its inmates have included Gandhi, Nehru, Subhas Chandra Bose, Tilak and Savarkar, and during the 1975–77 Emergency, Atal Bihari Vajpayee.',
      'Built by the British in 1871, it covers 512 acres and is Maharashtra’s largest prison; it even has egg-shaped cells for high-security prisoners.',
      'Mumbai 26/11 attacker Ajmal Kasab was hanged and buried here on 21 November 2012.',
      'Its in-house textile mill turns out about 5,000 garments a day, and inmates stitched the uniforms used in the 2009 film "Jail".',
    ],
    sources: ['https://en.wikipedia.org/wiki/Yerawada_Central_Jail'],
  },
  {
    id: 'pune-junction',
    name: 'Pune Junction',
    category: 'transit',
    match: 'Pune\\s*(Junction|Railway\\s*Station|Station)',
    building: 'Pune\\s*(Junction|Railway)',
    preferStation: true,
    lat: 18.5289, lon: 73.8743,
    wikipedia: 'Pune Junction railway station',
    wikidata: 'Q3632576',
    importance: 1,
    tagline: 'Home of the 1930 Deccan Queen',
    facts: [
      'The station opened in 1858, four years before the Bhor Ghat incline was finished in 1862 — so at first trains could not run all the way to Mumbai.',
      'The present station building dates from 1925.',
      'The Deccan Queen, introduced on 1 June 1930, was India’s first superfast train and the first with a women-only car and a dining car; it still runs daily to Mumbai.',
      'During COVID-19 the railway police put a robot called "Captain Arjun" on duty here to screen passengers.',
    ],
    sources: [
      'https://en.wikipedia.org/wiki/Pune_Junction_railway_station',
      'https://en.wikipedia.org/wiki/Deccan_Queen',
    ],
  },
  {
    id: 'salim-ali-sanctuary',
    name: 'Dr. Salim Ali Bird Sanctuary',
    category: 'park',
    match: 'Salim\\s*Ali',
    preferStation: false,
    lat: 18.5440, lon: 73.8975,
    wikipedia: null,
    wikidata: null,
    importance: 2,
    tagline: 'City bird sanctuary opened by Salim Ali',
    facts: [
      'Ecologist Prakash Gole founded it in 1973, and it was opened by the famous ornithologist Dr. Salim Ali himself.',
      'It lies on the Mula-Mutha riverbank between the Bund Garden and Kalyani Nagar bridges, and over 110 bird species have reportedly been recorded here, including migratory ruddy shelducks.',
      'The metro route and tree felling nearby have been flashpoints; residents protested the Kalyani Nagar metro alignment in 2018.',
    ],
    sources: [
      'https://somanytraveltales.com/bird-watching-in-dr-salim-ali-bird-sanctuary-pune/',
      'https://en.wikipedia.org/wiki/Kalyani_Nagar',
    ],
  },
  {
    id: 'deccan-college',
    name: 'Deccan College',
    category: 'education',
    match: 'Deccan\\s*College',
    building: 'Deccan\\s*College',
    preferStation: false,
    lat: 18.5489, lon: 73.8749,
    wikipedia: 'Deccan College Post-Graduate and Research Institute',
    wikidata: 'Q5248851',
    importance: 2,
    tagline: 'Founded 1821 with the Peshwa’s money',
    facts: [
      'It started on 6 October 1821 as the "Hindoo College", funded from the Peshwa’s old Dakshina Fund after the British annexed Peshwa territory.',
      'Its neo-Gothic main building near Yerawada was paid for by a ₹1 lakh gift from Sir Jamsetjee Jejeebhoy, 2nd Baronet; classes moved there in 1868.',
      'Past principals include William Wordsworth, grandson of the poet, and E. A. Wodehouse, brother of P. G. Wodehouse.',
      'After closing for lack of funds in 1934, it was reopened in 1939 by order of the Bombay High Court as a research institute; its archaeologists are now excavating Rakhigarhi, the largest Indus Valley site.',
      'It once had India’s oldest boat club, the Poonah Boat Club.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Deccan_College_Post-Graduate_and_Research_Institute'],
  },
  {
    id: 'yerawada-metro',
    name: 'Yerawada metro station',
    category: 'transit',
    match: 'Yer[a]?[wv]a?da',
    preferStation: true,
    lat: 18.5453, lon: 73.8865,
    wikipedia: 'Yerwada metro station',
    wikidata: 'Q124793268',
    importance: 3,
    tagline: 'A station facade saluting Gandhi',
    facts: [
      'Its facade shows the Dandi March and a charkha (spinning wheel) as a tribute to Gandhi, who was held in the nearby Yerwada jail.',
      'It was inaugurated with its neighbours on 6 March 2024, but repeated delays over its entry and exit points kept it closed until 21 August 2024.',
      'Once it opened, the airport feeder bus moved here from Ramwadi.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Yerwada_metro_station'],
  },
  {
    id: 'bund-garden-metro',
    name: 'Bund Garden metro station',
    category: 'transit',
    match: 'Bund\\s*Garden',
    preferStation: true,
    lat: 18.5402, lon: 73.8832,
    wikipedia: 'Bund Garden metro station',
    wikidata: 'Q124762850',
    importance: 3,
    tagline: 'Nature-themed Aqua Line stop',
    facts: [
      'Trial runs from here to Ramwadi began in September 2023, and it opened to passengers on 6 March 2024.',
      'Its facade design is inspired by elements of nature, a nod to the neighbouring garden.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Bund_Garden_metro_station'],
  },
  {
    id: 'nagar-road',
    name: 'Nagar Road',
    category: 'road',
    match: '^(Pune[\\s-]*)?(Ahmed)?Nagar\\s*Road$|Pune[\\s-]*Ahmednagar\\s*(Road|Highway)',
    preferStation: false,
    lat: 18.5599, lon: 73.9149,
    wikipedia: null,
    wikidata: null,
    importance: 2,
    tagline: 'Eastern highway, once called Koregaon Road',
    facts: [
      'It used to be called Koregaon Road because it leads to Koregaon Bhima village, which is how Koregaon Park got its name.',
      'Starting in Yerawada, it runs through Vadgaon Sheri, Kharadi and Wagholi towards Ahmednagar; Airport Road branches off it.',
      'The Aga Khan Palace stands on it, and Yerawada Central Jail and the Poona Club golf course lie just off it.',
    ],
    sources: [
      'https://en.wikipedia.org/wiki/Koregaon_Park',
      'https://en.wikipedia.org/wiki/List_of_roads_in_Pune',
      'https://en.wikipedia.org/wiki/National_Highway_753F_(India)',
    ],
  },
  {
    id: 'airport-road',
    name: 'Airport Road',
    category: 'road',
    match: '^Airport\\s*Road$',
    preferStation: false,
    lat: 18.5700, lon: 73.9000,
    wikipedia: null,
    wikidata: null,
    importance: 3,
    tagline: 'Spur from Nagar Road to Lohegaon',
    facts: [
      'It branches off Nagar Road in Yerawada and runs north to the airport at Lohegaon.',
      'The 18-hole Poona Club golf course, one of India’s oldest, sits on it (6, Airport Road).',
    ],
    sources: [
      'https://en.wikipedia.org/wiki/List_of_roads_in_Pune',
      'https://poonaclubltd.com/about-club/club-history/',
    ],
  },
  {
    id: 'koregaon-park-road',
    name: 'North Main Road',
    category: 'road',
    match: '^North\\s*Main\\s*Road$',
    preferStation: false,
    lat: 18.5396, lon: 73.8950,
    wikipedia: null,
    wikidata: null,
    importance: 3,
    tagline: 'Koregaon Park’s spine of bungalows and bars',
    facts: [
      'It runs parallel to South Main Road, and the numbered lanes connecting the two hold the homes of Pune’s business magnates, military officers and politicians.',
      'The lanes are lined with old British-era bungalows from the Koregaon Road Estate days.',
      'The German Bakery on this road was the target of the 13 February 2010 bombing that killed 18 people.',
    ],
    sources: [
      'https://en.wikipedia.org/wiki/List_of_roads_in_Pune',
      'https://en.wikipedia.org/wiki/Koregaon_Park',
    ],
  },
  {
    id: 'poona-golf',
    name: 'Poona Club Golf Course',
    category: 'park',
    match: 'Poona\\s*(Club\\s*)?Golf|Pune\\s*Club\\s*Golf',
    preferStation: false,
    lat: 18.5558, lon: 73.8866,
    wikipedia: null,
    wikidata: null,
    importance: 2,
    tagline: 'One of India’s oldest golf courses',
    facts: [
      'Tournaments have reportedly been played here since 1920; the first was the Royal Western India Turf Club Cup.',
      'When the British left India, the Poona Club considered giving up the golf grounds; a handful of enthusiasts saved the course.',
      'More than 30,000 trees have been planted since the course was relaid in 1980–85, and trees now line most of the fairways.',
      'The course once covered nearly 135 acres, but the government took part of the land for housing; it now covers about 90–96 acres.',
    ],
    sources: [
      'https://thegolfasia.com/golf-courses/poona-golf-club',
      'https://4moles.com/golf-courses/poona-club-golf-course-pune',
      'https://poonaclubltd.com/about-club/club-history/',
    ],
  },
  {
    id: 'ruby-hall',
    name: 'Ruby Hall Clinic',
    category: 'civic',
    match: '^Ruby\\s*Hall(\\s*Clinic)?$',
    building: 'Ruby\\s*Hall',
    preferStation: false,
    lat: 18.5334, lon: 73.8772,
    wikipedia: 'Ruby Hall Clinic',
    wikidata: 'Q7376324',
    importance: 3,
    tagline: 'Cardiologist’s clinic grown into major hospital',
    facts: [
      'Cardiologist Dr. Keki Byramjee Grant founded it in 1959; in 1966 he turned his private hospital into a public charitable trust.',
      'In 1999 it had more ICU beds (76) than any other hospital in India.',
      'The Aqua Line’s Ruby Hall Clinic metro station, named after the hospital, was the line’s eastern terminus from August 2023 until the extension to Ramwadi opened in March 2024.',
    ],
    sources: [
      'https://en.wikipedia.org/wiki/Ruby_Hall_Clinic',
      'https://en.wikipedia.org/wiki/Aqua_Line_(Pune_Metro)',
    ],
  },
  {
    id: 'pune-metro-aqua',
    name: 'Pune Metro Aqua Line',
    category: 'transit',
    match: 'Aqua\\s*Line|Line\\s*2|Vanaz[\\s-–]*Ramwadi',
    preferStation: false,
    lat: 18.5402, lon: 73.8832,
    wikipedia: 'Aqua Line (Pune Metro)',
    wikidata: 'Q59155699',
    importance: 2,
    tagline: 'Elevated east–west metro, Vanaz to Ramwadi',
    facts: [
      'The fully elevated line runs 14.66 km with 16 stations, from Vanaz in the west to Ramwadi in the east.',
      'It opened in three stages: Vanaz–Garware College in March 2022, on to Ruby Hall Clinic in August 2023, and to Ramwadi in March 2024.',
      'Its maintenance depot near Vanaz stands on land that used to be a garbage depot.',
      'Trains run on Alstom’s Urbalis 400 CBTC signalling, supplied under a €90 million contract that also covered two Mumbai Metro lines.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Aqua_Line_(Pune_Metro)'],
  },
  {
    id: 'sassoon-hospital',
    name: 'Sassoon General Hospital',
    category: 'civic',
    match: 'Sassoon\\s*(General\\s*)?Hospital',
    building: 'Sassoon',
    preferStation: false,
    lat: 18.5257, lon: 73.8719,
    wikipedia: 'Sassoon Hospital',
    wikidata: 'Q7425789',
    importance: 2,
    tagline: 'Where Meher Baba was born',
    facts: [
      'It was built in 1867 with a donation from Jewish philanthropist David Sassoon, and originally held just 144 patients (today it has over 1,500 beds).',
      'Mahatma Gandhi had his appendix removed here on 12 January 1924.',
      'The spiritual master Meher Baba was born here on 25 February 1894.',
      'The 1909 Jacob Sassoon wing has Royal Doulton tile panels of nursery rhymes and fairy tales, installed to distract sick children.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Sassoon_Hospital'],
  },
  {
    id: 'ohel-david',
    name: 'Ohel David Synagogue (Lal Deval)',
    category: 'religious',
    match: 'Ohel\\s*David|La+l\\s*De(v|u)a?l',
    building: 'Ohel\\s*David|Synagogue',
    preferStation: false,
    lat: 18.5193, lon: 73.8747,
    wikipedia: 'Ohel David Synagogue',
    wikidata: 'Q7080652',
    importance: 2,
    tagline: 'The “Red Temple” of Pune Camp',
    facts: [
      'Locals call it "Lal Deval" — Marathi for "Red Temple" — after its red-brick exterior.',
      'Its 90-foot clock tower has a clock made in London especially for the synagogue, and it closely matches the tower on Sassoon Hospital by the same architect, Henry St Clair Wilkins.',
      'Patron David Sassoon died in Pune in 1864, three years before it was consecrated in 1867; his Gothic mausoleum stands in the compound.',
      'Wikipedia describes it as Asia’s largest synagogue outside Israel.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Ohel_David_Synagogue'],
  },
  {
    id: 'st-patricks-cathedral',
    name: "St. Patrick's Cathedral",
    category: 'religious',
    match: "St\\.?\\s*Patrick'?s\\s*(Cathedral|Church)",
    building: 'Patrick',
    preferStation: false,
    lat: 18.5088, lon: 73.8982,
    wikipedia: "St. Patrick's Cathedral, Pune",
    wikidata: 'Q7595055',
    importance: 3,
    tagline: 'Built for Irish soldiers in 1850',
    facts: [
      'It was built in 1850 mainly for Irish Catholic soldiers stationed nearby, who each gave a month’s salary towards it.',
      'The roof collapsed on 15 July 1984; architect Charles Correa designed the curved vaulted roof that replaced the original pointed one.',
      'It became a cathedral in 1887, after Poona was made a diocese.',
    ],
    sources: ["https://en.wikipedia.org/wiki/St._Patrick%27s_Cathedral,_Pune"],
  },
  {
    id: 'empress-garden',
    name: 'Empress Botanical Garden',
    category: 'park',
    match: 'Empress\\s*(Botanical\\s*)?Garden',
    preferStation: false,
    lat: 18.5131, lon: 73.8978,
    wikipedia: null,
    wikidata: 'Q97487028',
    importance: 2,
    tagline: '39 acres of colonial-era botanical garden',
    facts: [
      'In the 19th century it was reportedly a "Soldiers’ Garden", one of many set up to keep British troops busy and away from the canteen liquor, while growing vegetables for their rations.',
      'It is named after Queen Victoria, Empress of India.',
      'It is run by the Agri-Horticultural Society of Western India and has around 180 tree species, including a 250–300-year-old banyan and a baobab.',
    ],
    sources: [
      'https://empressgarden.org/about/',
      'https://www.atlasobscura.com/places/empress-botanical-garden',
    ],
  },
  {
    id: 'pune-race-course',
    name: 'Pune Race Course',
    category: 'park',
    match: '(Pune|Poona)\\s*Race\\s*Course|^Race\\s*Course$|Royal Western India Turf Club',
    preferStation: false,
    lat: 18.5101, lon: 73.8930,
    wikipedia: 'Pune Race Course',
    wikidata: 'Q5455467',
    importance: 3,
    tagline: 'Monsoon horse racing since 1830',
    facts: [
      'Built in 1830, it covers 118.5 acres of land that is still controlled by the Indian Army.',
      'Unusually, the racing season runs during the monsoon, from July to October, and includes the Pune Derby.',
      'It is managed by the Royal Western India Turf Club; extra stables are about 1 km away, near Empress Garden.',
    ],
    sources: ['https://en.wikipedia.org/wiki/Pune_Race_Course'],
  },
];
